version: '3'
services:
  db:
    image: postgres
    restart: always
    ports:
     - "35432:5432"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: fuelmeter
      POSTGRES_PASSWORD: fuelmeter
